### ISSUE TITLE
Uncaught TypeError: (intermediate value) is not a function (...ClientImpl._push)

### ISSUE THREAD

**Issue by fdbeirao** [kevinbgreene/indeksd#1]
Hello! First of all, congratulations on this package, it seems pretty well put together!

I am running into an issue where I observe this message on my console:

```
Uncaught TypeError: (intermediate value) is not a function
    at UserAudiosClientImpl._push (AudioFiles.ts:140:39)
    at DBAddRequest.onsuccess (AudioFiles.ts:185:18)
```

My schema is super simple, since I am just poking around:

```
database AudioFiles @version(1) {
    table UserAudios {
        @key @unique id: string;
        data: Blob;
    }
}
```

This seems to be caused by the following piece of autogenerated code:

```
140: (this.#listeners.get('change')?.forEach)((callback) => {
```

The error seems to be due to the fact that the `#listeners` Map can return an `undefined` for a non-existing key. The `?.` operator propagates the undefined, and then we try to invoke a function on an `undefined`.

I am a bit confused, since on your unit tests, I see a `test.solution.txt` which uses a [different strategy](https://github.com/kevinbgreene/indeksd/blob/main/src/tests/fixtures/solutions/test.solution.txt#L497) from my auto-generated code.

I am using version `0.0.17`

I think I could add a phantom subscription as a work around, but I think the `if` approach on the unit tests is a better one. Perhaps you're missing publishing the latest version of the code to npm?

Once again, thank you! :)

**Comment by fdbeirao** [comment]
I confirm that adding the following code is a work-around for now:

```
_audioFilesClient.ravlt.subscribe("add", () => {});
_audioFilesClient.ravlt.subscribe("change", () => {});
```

**Comment by aaditmshah** [comment]
I'm also getting the same error in my generated code. In fact, my linter complains about it.

![Cannot invoke an object which is possibly 'undefined'.](https://github.com/kevinbgreene/indeksd/assets/813511/4fd3d22d-872e-4d4b-a885-daeb99fbe264)

Using the optional method chaining operator fixes this problem.

![Errors resolved after using optional method chaining.](https://github.com/kevinbgreene/indeksd/assets/813511/c1138b6c-5b7b-4344-ba51-90fc829c9b1b)

The fix seems easy enough. I'll take the liberty to fix the problem and create a PR.

**Comment by aaditmshah** [comment]
@fdbeirao I created a fork of `indeksd` called `indeksddb`.

https://github.com/aaditmshah/indeksddb

My fork contains the bug fix for this issue. So, you can use `indeksddb` for now. It's a drop-in replacement for `indeksd`.

```shell
npm r -D indeksd
npm i -D indeksddb
```

Let me know whether this solves your problem.

**Comment by fdbeirao** [comment]
@aaditmshah thank you for this effort. Unfortunately the project where I was using `indeksdb` has come to a stop, so I won't be needing this particular tool for now. If I need it again in the future, I will be sure to keep your fork in mind.
Cheers!
